version: '3.8'

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - ..:/workspace:cached
    command: sleep infinity
    network_mode: service:db

  db:
    image: mongo:latest
    restart: unless-stopped
    volumes:
      - dataDB:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 123
      MONGO_INITDB_DATABASE: main
      
  express:
    image: mongo-express
    environment:
      ME_CONFIG_MONGODB_SERVER: db
      ME_CONFIG_BASICAUTH_USERNAME: root
      ME_CONFIG_BASICAUTH_PASSWORD: 123
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: 123
    depends_on:
      - db
    restart: unless-stopped
    network_mode: service:db


  #mailhog:
  #  image: mailhog/mailhog
  #  command: [ "-storage=maildir", "-maildir-path=/home/mailhog/mail/" ]
  #  user: root
  #  volumes:
  #    - dataMail:/home/mailhog/mail/
  #  restart: unless-stopped
  #  network_mode: service:db

  #minio:
  #  image: minio/minio
  #  volumes:
  #    - dataStorage:/data
  #  environment:
  #      MINIO_ROOT_USER: minioadmin
  #      MINIO_ROOT_PASSWORD: minioadmin
  #  entrypoint: sh
  #  command: -c "mkdir -p /data/static && minio server /data --console-address ":9001""
  #  restart: unless-stopped
  #  network_mode: service:db

volumes:
    dataDB: { }
    dataMail: { }
    dataStorage: { }